IF
  True()
THEN
  RESPONSE #100
    CutSceneId("TSUJATH")
    ReallyForceSpell(Myself,WIZARD_ABI_DALZIMS_HORRID_WILTING)
    ScreenShake([5.5],5)
    ReallyForceSpell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)
    Wait(1)
    DropInventory()
    ReallyForceSpell(Myself,RED_EFFECT)

    Wait(2)

    ActionOverride("TSUJATH",LeaveParty())
    ActionOverride("TSUJATH",ReallyForceSpell(Myself,TRANSFORMATION_DEATH))
    EndCutSceneMode()

    Wait(1)
    Kill("TSUJATH")
END


